services:
#--- PostgreSQL con timescaledb ---
  timescaledb:
    image: timescale/timescaledb:latest-pg14
    container_name: finance_db
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=finance_bench
    ports:
      - "5432:5432"
    volumes:
      - ./timescale_data:/var/lib/postgresql/data
#--- MongoDB ---
  mongo:
      image: mongo:latest
      container_name: finance_mongo
      restart: always
      ports:
        - "27017:27017"
      
      volumes:
        - ./mongo_data:/data/db